/**
 * 職業ごとのイメージ画像。
 * public/images/careers/{slug}.jpg に配置する。
 * 未登録の職業はデフォルト画像を表示。
 */
export const CAREER_IMAGE_SLUGS: Record<string, string> = {
  "ソフトウェアエンジニア": "software-engineer",
  "データサイエンティスト": "data-scientist",
  "AIエンジニア": "ai-engineer",
  "インフラ・クラウドエンジニア": "infra-engineer",
  "セキュリティアナリスト": "security-analyst",
  "QAエンジニア": "qa-engineer",
  "プロダクトマネージャー": "product-manager",
  "UI/UXデザイナー": "ui-ux-designer",
  "グラフィックデザイナー": "graphic-designer",
  "イラストレーター": "illustrator",
  "映像クリエイター": "video-creator",
  "フォトグラファー": "photographer",
  "コピーライター": "copywriter",
  "編集者": "editor",
  "ゲームプランナー": "game-planner",
  "作曲家・サウンドクリエイター": "composer",
  "建築家": "architect",
  "インテリアコーディネーター": "interior-coordinator",
  "ランドスケープデザイナー": "landscape-designer",
  "研究者（自然科学）": "researcher",
  "データアナリスト": "data-analyst",
  "薬剤師": "pharmacist",
  "医師": "doctor",
  "看護師": "nurse",
  "理学療法士": "physical-therapist",
  "臨床心理士・カウンセラー": "counselor",
  "管理栄養士": "dietitian",
  "介護福祉士": "caregiver",
  "保育士": "nursery-teacher",
  "小学校・中学校教員": "school-teacher",
  "キャリアコンサルタント": "career-consultant",
  "スポーツトレーナー": "sports-trainer",
  "図書館司書": "librarian",
  "経営コンサルタント": "management-consultant",
  "起業家": "entrepreneur",
  "営業（法人）": "sales",
  "マーケター": "marketer",
  "広報・PR": "pr",
  "人事・採用担当": "hr",
  "経理・財務": "accounting",
  "公認会計士": "cpa",
  "税理士": "tax-accountant",
  "ファイナンシャルプランナー": "financial-planner",
  "アクチュアリー": "actuary",
  "弁護士": "lawyer",
  "行政書士・司法書士": "judicial-scrivener",
  "公務員（行政職）": "public-servant",
  "警察官": "police-officer",
  "消防士・救急救命士": "firefighter",
  "自衛官": "sdf-officer",
  "パイロット": "pilot",
  "電気・機械エンジニア": "mechanical-engineer",
  "自動車整備士": "car-mechanic",
  "建築施工管理": "construction-manager",
  "職人・伝統工芸": "craftsman",
  "農業・林業従事者": "farmer",
  "料理人・パティシエ": "chef",
  "バリスタ・カフェ経営": "barista",
  "ホテルスタッフ": "hotel-staff",
  "ツアープランナー": "tour-planner",
  "美容師・スタイリスト": "hairdresser",
  "獣医師": "veterinarian",
  "トリマー・動物飼育員": "animal-keeper",
  "環境・サステナビリティ専門家": "sustainability-expert",
  "翻訳家・通訳": "translator",
  "ジャーナリスト": "journalist",
  "アナウンサー・司会": "announcer",
  "SNS・コンテンツクリエイター": "content-creator",
  "物流・サプライチェーン管理": "logistics",
  "秘書・オフィスマネージャー": "office-manager",
  "カスタマーサクセス": "customer-success",
};

export const DEFAULT_CAREER_IMAGE = "/images/careers/default.jpg";

export function careerImage(name: string): string {
  const slug = CAREER_IMAGE_SLUGS[name];
  return slug ? `/images/careers/${slug}.jpg` : DEFAULT_CAREER_IMAGE;
}
