/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GamesRouteImport } from './routes/games'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as QuizzesRouteImport } from './routes/quizzes'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as GameKanjiRouteImport } from './routes/game.kanji'
import { Route as GameKokkiRouteImport } from './routes/game.kokki'
import { Route as GameKotowazaRouteImport } from './routes/game.kotowaza'
import { Route as QuizIdRouteImport } from './routes/quiz.$id'
import { Route as QuizTekishokuRouteImport } from './routes/quiz.tekishoku'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesRoute = QuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const GameKanjiRoute = GameKanjiRouteImport.update({
  id: '/game/kanji',
  path: '/game/kanji',
  getParentRoute: () => rootRouteImport,
} as any)
const GameKokkiRoute = GameKokkiRouteImport.update({
  id: '/game/kokki',
  path: '/game/kokki',
  getParentRoute: () => rootRouteImport,
} as any)
const GameKotowazaRoute = GameKotowazaRouteImport.update({
  id: '/game/kotowaza',
  path: '/game/kotowaza',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizIdRoute = QuizIdRouteImport.update({
  id: '/quiz/$id',
  path: '/quiz/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizTekishokuRoute = QuizTekishokuRouteImport.update({
  id: '/quiz/tekishoku',
  path: '/quiz/tekishoku',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/games': typeof GamesRoute
  '/privacy': typeof PrivacyRoute
  '/quizzes': typeof QuizzesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/game/kanji': typeof GameKanjiRoute
  '/game/kokki': typeof GameKokkiRoute
  '/game/kotowaza': typeof GameKotowazaRoute
  '/quiz/$id': typeof QuizIdRoute
  '/quiz/tekishoku': typeof QuizTekishokuRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/games': typeof GamesRoute
  '/privacy': typeof PrivacyRoute
  '/quizzes': typeof QuizzesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/game/kanji': typeof GameKanjiRoute
  '/game/kokki': typeof GameKokkiRoute
  '/game/kotowaza': typeof GameKotowazaRoute
  '/quiz/$id': typeof QuizIdRoute
  '/quiz/tekishoku': typeof QuizTekishokuRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/games': typeof GamesRoute
  '/privacy': typeof PrivacyRoute
  '/quizzes': typeof QuizzesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/game/kanji': typeof GameKanjiRoute
  '/game/kokki': typeof GameKokkiRoute
  '/game/kotowaza': typeof GameKotowazaRoute
  '/quiz/$id': typeof QuizIdRoute
  '/quiz/tekishoku': typeof QuizTekishokuRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/games'
    | '/privacy'
    | '/quizzes'
    | '/sitemap.xml'
    | '/game/kanji'
    | '/game/kokki'
    | '/game/kotowaza'
    | '/quiz/$id'
    | '/quiz/tekishoku'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/games'
    | '/privacy'
    | '/quizzes'
    | '/sitemap.xml'
    | '/game/kanji'
    | '/game/kokki'
    | '/game/kotowaza'
    | '/quiz/$id'
    | '/quiz/tekishoku'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/games'
    | '/privacy'
    | '/quizzes'
    | '/sitemap.xml'
    | '/game/kanji'
    | '/game/kokki'
    | '/game/kotowaza'
    | '/quiz/$id'
    | '/quiz/tekishoku'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  GamesRoute: typeof GamesRoute
  PrivacyRoute: typeof PrivacyRoute
  QuizzesRoute: typeof QuizzesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  GameKanjiRoute: typeof GameKanjiRoute
  GameKokkiRoute: typeof GameKokkiRoute
  GameKotowazaRoute: typeof GameKotowazaRoute
  QuizIdRoute: typeof QuizIdRoute
  QuizTekishokuRoute: typeof QuizTekishokuRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes': {
      id: '/quizzes'
      path: '/quizzes'
      fullPath: '/quizzes'
      preLoaderRoute: typeof QuizzesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/kanji': {
      id: '/game/kanji'
      path: '/game/kanji'
      fullPath: '/game/kanji'
      preLoaderRoute: typeof GameKanjiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/kokki': {
      id: '/game/kokki'
      path: '/game/kokki'
      fullPath: '/game/kokki'
      preLoaderRoute: typeof GameKokkiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/kotowaza': {
      id: '/game/kotowaza'
      path: '/game/kotowaza'
      fullPath: '/game/kotowaza'
      preLoaderRoute: typeof GameKotowazaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$id': {
      id: '/quiz/$id'
      path: '/quiz/$id'
      fullPath: '/quiz/$id'
      preLoaderRoute: typeof QuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/tekishoku': {
      id: '/quiz/tekishoku'
      path: '/quiz/tekishoku'
      fullPath: '/quiz/tekishoku'
      preLoaderRoute: typeof QuizTekishokuRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  GamesRoute: GamesRoute,
  PrivacyRoute: PrivacyRoute,
  QuizzesRoute: QuizzesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  GameKanjiRoute: GameKanjiRoute,
  GameKokkiRoute: GameKokkiRoute,
  GameKotowazaRoute: GameKotowazaRoute,
  QuizIdRoute: QuizIdRoute,
  QuizTekishokuRoute: QuizTekishokuRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
